Contributing to oshinko-temaki
==============================

All pull requests and issues welcome =)

If you would like to contribute a change to this respository, please fork it,
create a branch for your feature, and then open a pull request with your
forked branch against the master branch in the upstream repository.

A note on generated files
-------------------------

The files `AUTHORS` and `ChangeLog` are generated by the
[Python Build Reasonableness (pbr)](https://docs.openstack.org/pbr/latest/)
tooling. They are generated for each release and included in the repository
as a convenience to people who might be browsing the contents. They should
not be updated outside of a release without extenuating circumstances.
